"""initial_schema

Revision ID: 50cce3ecfaee
Revises: 
Create Date: 2026-03-24 15:18:02.341473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50cce3ecfaee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('plano', sa.String(length=20), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('alertas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('referencia_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('data_alerta', sa.Date(), nullable=False),
    sa.Column('visto', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_data_alerta'), 'alertas', ['data_alerta'], unique=False)
    op.create_index(op.f('ix_alertas_usuario_id'), 'alertas', ['usuario_id'], unique=False)
    op.create_table('contas_fixas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dia_vencimento', sa.SmallInteger(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_fixas_usuario_id'), 'contas_fixas', ['usuario_id'], unique=False)
    op.create_table('dividas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('credor', sa.String(length=150), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('parcelas_restantes', sa.SmallInteger(), nullable=False),
    sa.Column('taxa_juros_mensal', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('data_prox_vencimento', sa.Date(), nullable=False),
    sa.Column('quitada', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividas_usuario_id'), 'dividas', ['usuario_id'], unique=False)
    op.create_table('planos_acao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('conteudo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conteudo_texto', sa.Text(), nullable=False),
    sa.Column('estrategia', sa.String(length=20), nullable=True),
    sa.Column('data_livre_prevista', sa.Date(), nullable=True),
    sa.Column('feedback', sa.SmallInteger(), nullable=True),
    sa.Column('feedback_texto', sa.Text(), nullable=True),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planos_acao_criado_em'), 'planos_acao', ['criado_em'], unique=False)
    op.create_index(op.f('ix_planos_acao_usuario_id'), 'planos_acao', ['usuario_id'], unique=False)
    op.create_table('rendas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frequencia', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rendas_usuario_id'), 'rendas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rendas_usuario_id'), table_name='rendas')
    op.drop_table('rendas')
    op.drop_index(op.f('ix_planos_acao_usuario_id'), table_name='planos_acao')
    op.drop_index(op.f('ix_planos_acao_criado_em'), table_name='planos_acao')
    op.drop_table('planos_acao')
    op.drop_index(op.f('ix_dividas_usuario_id'), table_name='dividas')
    op.drop_table('dividas')
    op.drop_index(op.f('ix_contas_fixas_usuario_id'), table_name='contas_fixas')
    op.drop_table('contas_fixas')
    op.drop_index(op.f('ix_alertas_usuario_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_data_alerta'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
