"""add_telefone_to_usuarios

Revision ID: 6dda92d1d37c
Revises: 852d94800f45
Create Date: 2026-04-10 10:23:43.840814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dda92d1d37c'
down_revision: Union[str, None] = '852d94800f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('telefone', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_usuarios_telefone'), 'usuarios', ['telefone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_telefone'), table_name='usuarios')
    op.drop_column('usuarios', 'telefone')
    # ### end Alembic commands ###
