"""add_investimentos

Revision ID: 852d94800f45
Revises: aaec3e73ca7d
Create Date: 2026-04-10 09:50:55.335615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852d94800f45'
down_revision: Union[str, None] = 'aaec3e73ca7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investimentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('instituicao', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('preco_medio', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_investido', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_atual', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('data_aplicacao', sa.Date(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investimentos')
    # ### end Alembic commands ###
