"""add_data_inicio_contrato_and_data_primeira_parcela_to_dividas

Revision ID: fe6c891bab5c
Revises: b3c4d5e6f7a8
Create Date: 2026-04-07 09:16:35.758513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6c891bab5c'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividas', sa.Column('data_inicio_contrato', sa.Date(), nullable=True))
    op.add_column('dividas', sa.Column('data_primeira_parcela', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dividas', 'data_primeira_parcela')
    op.drop_column('dividas', 'data_inicio_contrato')
    # ### end Alembic commands ###
